store_backend_homepage:
    path:     /hello/{name}
    defaults: { _controller: StoreBackendBundle:Default:index }

store_backend_index:
    path:     /dashboard/{name}
    defaults: { _controller: StoreBackendBundle:Main:index, name: null }

store_backend_product:
    path:     /product/{product}
    defaults: { _controller: StoreBackendBundle:Main:product, product: null }

store_backend_statics:
    resource: "@StoreBackendBundle/Resources/config/statics.yml"
    prefix:   /
