<?php

namespace Proxies\__CG__\Store\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Store\BackendBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'ref', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'title', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'summary', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'composition', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'taxe', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'quantity', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'active', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'dateActive', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'cover', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'shop', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'position', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'slug', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'dateCreated', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'dateUpdated', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'jeweler', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'user', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'order', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'business', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'category', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'cms', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'product2', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'supplier', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'tag');
        }

        return array('__isInitialized__', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'ref', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'title', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'summary', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'composition', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'taxe', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'quantity', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'active', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'dateActive', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'cover', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'shop', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'position', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'slug', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'dateCreated', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'dateUpdated', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'jeweler', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'user', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'order', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'business', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'category', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'cms', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'product2', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'supplier', '' . "\0" . 'Store\\BackendBundle\\Entity\\Product' . "\0" . 'tag');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRef($ref)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRef', array($ref));

        return parent::setRef($ref);
    }

    /**
     * {@inheritDoc}
     */
    public function getRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRef', array());

        return parent::getRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSummary($summary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSummary', array($summary));

        return parent::setSummary($summary);
    }

    /**
     * {@inheritDoc}
     */
    public function getSummary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSummary', array());

        return parent::getSummary();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setComposition($composition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComposition', array($composition));

        return parent::setComposition($composition);
    }

    /**
     * {@inheritDoc}
     */
    public function getComposition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComposition', array());

        return parent::getComposition();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxe($taxe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxe', array($taxe));

        return parent::setTaxe($taxe);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxe', array());

        return parent::getTaxe();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', array($quantity));

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', array());

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateActive($dateActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateActive', array($dateActive));

        return parent::setDateActive($dateActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateActive', array());

        return parent::getDateActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setCover($cover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCover', array($cover));

        return parent::setCover($cover);
    }

    /**
     * {@inheritDoc}
     */
    public function getCover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCover', array());

        return parent::getCover();
    }

    /**
     * {@inheritDoc}
     */
    public function setShop($shop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShop', array($shop));

        return parent::setShop($shop);
    }

    /**
     * {@inheritDoc}
     */
    public function getShop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShop', array());

        return parent::getShop();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($dateCreated));

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdated($dateUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdated', array($dateUpdated));

        return parent::setDateUpdated($dateUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdated', array());

        return parent::getDateUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setJeweler(\Store\BackendBundle\Entity\Jeweler $jeweler = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJeweler', array($jeweler));

        return parent::setJeweler($jeweler);
    }

    /**
     * {@inheritDoc}
     */
    public function getJeweler()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJeweler', array());

        return parent::getJeweler();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\Store\BackendBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', array($user));

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\Store\BackendBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', array($user));

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\Store\BackendBundle\Entity\Orders $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', array($order));

        return parent::addOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\Store\BackendBundle\Entity\Orders $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', array($order));

        return parent::removeOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', array());

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function addBusiness(\Store\BackendBundle\Entity\Business $business)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBusiness', array($business));

        return parent::addBusiness($business);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBusiness(\Store\BackendBundle\Entity\Business $business)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBusiness', array($business));

        return parent::removeBusiness($business);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusiness()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusiness', array());

        return parent::getBusiness();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\Store\BackendBundle\Entity\Category $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', array($category));

        return parent::addCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\Store\BackendBundle\Entity\Category $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', array($category));

        return parent::removeCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addCm(\Store\BackendBundle\Entity\Cms $cms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCm', array($cms));

        return parent::addCm($cms);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCm(\Store\BackendBundle\Entity\Cms $cms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCm', array($cms));

        return parent::removeCm($cms);
    }

    /**
     * {@inheritDoc}
     */
    public function getCms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCms', array());

        return parent::getCms();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct2(\Store\BackendBundle\Entity\Product $product2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct2', array($product2));

        return parent::addProduct2($product2);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct2(\Store\BackendBundle\Entity\Product $product2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct2', array($product2));

        return parent::removeProduct2($product2);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct2', array());

        return parent::getProduct2();
    }

    /**
     * {@inheritDoc}
     */
    public function addSupplier(\Store\BackendBundle\Entity\Supplier $supplier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSupplier', array($supplier));

        return parent::addSupplier($supplier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSupplier(\Store\BackendBundle\Entity\Supplier $supplier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSupplier', array($supplier));

        return parent::removeSupplier($supplier);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplier', array());

        return parent::getSupplier();
    }

    /**
     * {@inheritDoc}
     */
    public function addTag(\Store\BackendBundle\Entity\Tag $tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTag', array($tag));

        return parent::addTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTag(\Store\BackendBundle\Entity\Tag $tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTag', array($tag));

        return parent::removeTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTag', array());

        return parent::getTag();
    }

}
