
store_backend_cms_list:
    path:     /list
    defaults: { _controller: StoreBackendBundle:CMS:list }

store_backend_cms_view:
    path:     /view/{id}/{name}
    defaults: { _controller: StoreBackendBundle:CMS:view }
    requirements:
      id: \d+
      _method: GET

# Remove a CMS
store_backend_cms_remove:
    path: /remove/{id}
    defaults: { _controller:StoreBackendBundle:CMS:remove }
    requirements:
     id: \d+