# Page list of Product
store_backend_product_list:
    path:     /list
    defaults: { _controller: StoreBackendBundle:Product:list }

store_backend_product_view:
    path:     /view/{id}
    defaults: { _controller: StoreBackendBundle:Product:view }
    requirements:
      id: \d+
      _method: GET

# Remove a Product
store_backend_product_remove:
    path: /remove/{id}
    defaults: { _controller:StoreBackendBundle:Product:remove }
    requirements:
     id: \d+