# Page list of Product
store_backend_product_list:
    path:     /list
    defaults: { _controller: StoreBackendBundle:Product:list }

store_backend_product_view:
    path:     /view/{id}/{name}
    defaults: { _controller: StoreBackendBundle:Product:view }
    requirements:
      id: \d+
      name: "[a-zA-Z0-9-]{5,30}"
      _method: GET